version: "3.7"

services:

    php:
        container_name: tce-php
        build: docker/php
        working_dir: /var/www/tce
        volumes:
            - ./:/var/www/tce
        extra_hosts:
            - "host.docker.internal:host-gateway"
